using CCP.Modules.Documents.Application.Abstractions;
using Microsoft.Extensions.Options;

namespace CCP.Modules.Documents.Infrastructure.Storage;

/// <summary>Where the local provider keeps its files.</summary>
public sealed class LocalStorageOptions
{
    public const string SectionName = "Documents:LocalStorage";

    /// <summary>
    /// The directory the objects live under.
    /// <para>
    /// Defaults to a folder beside the application. On a container that means
    /// the files disappear when it restarts, which is correct for development
    /// and is why production points this at a mounted volume — or, better, uses
    /// object storage and never touches this provider at all.
    /// </para>
    /// </summary>
    public string RootPath { get; set; } =
        Path.Combine(AppContext.BaseDirectory, "document-store");
}

/// <summary>
/// Objects as files in a directory.
/// <para>
/// The development implementation, and the fallback when no object storage is
/// configured. It is deliberately the simplest thing that satisfies the
/// interface: no pre-signed URLs, no lifecycle rules, no redundancy.
/// </para>
/// <para>
/// <b>It is not a toy.</b> A small company running one instance with a mounted
/// volume can use it in production and be no worse off than it was with a file
/// share — as long as somebody backs the volume up, which is precisely the thing
/// object storage does for you and this does not.
/// </para>
/// </summary>
public sealed class LocalFileStorageProvider : IDocumentStorageProvider
{
    private readonly string _rootPath;

    public LocalFileStorageProvider(IOptions<LocalStorageOptions> options)
    {
        ArgumentNullException.ThrowIfNull(options);

        _rootPath = options.Value.RootPath;

        Directory.CreateDirectory(_rootPath);
    }

    public string Name => "local";

    public async Task StoreAsync(
        string objectKey,
        Stream content,
        string contentType,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(content);

        string path = ResolvePath(objectKey);

        Directory.CreateDirectory(Path.GetDirectoryName(path)!);

        // CreateNew, not Create. An object key that already exists means either
        // a collision in twenty random bytes or a bug, and both deserve an
        // exception rather than silently overwriting somebody else's document.
        await using var file = new FileStream(
            path, FileMode.CreateNew, FileAccess.Write, FileShare.None,
            bufferSize: 64 * 1024, useAsync: true);

        await content.CopyToAsync(file, cancellationToken);
    }

    public Task<Stream?> OpenAsync(string objectKey, CancellationToken cancellationToken = default)
    {
        string path = ResolvePath(objectKey);

        if (!File.Exists(path))
        {
            return Task.FromResult<Stream?>(null);
        }

        Stream stream = new FileStream(
            path, FileMode.Open, FileAccess.Read, FileShare.Read,
            bufferSize: 64 * 1024, useAsync: true);

        return Task.FromResult<Stream?>(stream);
    }

    public Task DeleteAsync(string objectKey, CancellationToken cancellationToken = default)
    {
        string path = ResolvePath(objectKey);

        if (File.Exists(path))
        {
            File.Delete(path);
        }

        return Task.CompletedTask;
    }

    /// <summary>
    /// Always null: a directory on a disk has no way to hand out a URL.
    /// <para>
    /// Which is what the nullable return is for. The caller streams the content
    /// instead, and nothing above this line has to know which kind of store it
    /// is talking to.
    /// </para>
    /// </summary>
    public Task<Uri?> TryCreateReadUrlAsync(
        string objectKey,
        string fileName,
        string contentType,
        TimeSpan lifetime,
        CancellationToken cancellationToken = default)
        => Task.FromResult<Uri?>(null);

    /// <summary>
    /// Turns an object key into a path, and refuses anything that could escape.
    /// <para>
    /// The keys are generated by the Platform and contain nothing but hex and
    /// one separator, so this check should never fire. It is here because "this
    /// value is always safe" is a statement about today's callers, and the cost
    /// of being wrong once is every file on the disk.
    /// </para>
    /// </summary>
    private string ResolvePath(string objectKey)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(objectKey);

        string root = Path.GetFullPath(_rootPath);
        string candidate = Path.GetFullPath(Path.Combine(root, objectKey));

        if (!candidate.StartsWith(root, StringComparison.Ordinal))
        {
            throw new InvalidOperationException(
                $"The object key '{objectKey}' resolves outside the document store.");
        }

        return candidate;
    }
}
