using System.Buffers.Text;
using System.Text;
using System.Text.Json;
using CCP.Kernel.Results;
using CCP.Modules.Identity.Application;
using CCP.Modules.Identity.Application.Abstractions;
using CCP.Modules.Identity.Domain.Users;
using CCP.Modules.Identity.Infrastructure.Security;
using Microsoft.Extensions.Options;

namespace CCP.Modules.Identity.UnitTests;

/// <summary>
/// The passkey verifier, against a registration and a sign-in captured from
/// Chrome's own WebAuthn implementation.
/// <para>
/// <b>The vectors are real, and that is the point.</b> A fixture generated by
/// the same understanding that wrote the verifier proves only that the
/// understanding is self-consistent, and there are several places to be
/// confidently wrong in both at once: the ordering of a CBOR map, the DER
/// wrapping of an ECDSA signature, where the attested credential data begins
/// inside the authenticator data. These came out of a browser
/// (<c>frontend/scripts/capture-webauthn-vectors.mjs</c>), so accepting them
/// means accepting what a browser produces.
/// </para>
/// <para>
/// <b>Most of what follows is refusals.</b> A verifier that accepts a genuine
/// assertion and also accepts a tampered one is worse than no verifier, because
/// it looks like security. Every check the implementation makes is broken here
/// on purpose and expected to fail.
/// </para>
/// </summary>
public sealed class WebAuthnVerifierTests
{
    private static readonly Vectors Captured = Vectors.Load();

    private static WebAuthnVerifier VerifierFor(
        string relyingPartyId = "localhost",
        string? origin = null)
        => new(Options.Create(new IdentityOptions
        {
            WebAuthn = new WebAuthnOptions
            {
                RelyingPartyId = relyingPartyId,
                Origins = [origin ?? Captured.Origin],
            },
        }));

    // -----------------------------------------------------------------------
    // Registration
    // -----------------------------------------------------------------------

    [Fact]
    public void AcceptsARegistrationChromeProduced()
    {
        Result<VerifiedRegistration> result = VerifierFor().VerifyRegistration(
            Captured.RegistrationEvidence(),
            Captured.Registration.Challenge);

        Assert.True(result.IsSuccess, result.IsFailure ? result.Error.Code : null);

        // The identifier the browser reported, which is what a sign-in will
        // later be looked up by.
        Assert.Equal(Captured.Registration.CredentialId, result.Value.CredentialId);

        // ES256. Every platform authenticator worth the name produces this.
        Assert.Equal(-7, result.Value.Algorithm);

        // The authenticator said it verified the person. Without this the
        // credential is one factor and must not be stored.
        Assert.True(result.Value.UserVerified);

        Assert.NotEmpty(result.Value.PublicKey);
    }

    [Fact]
    public void RefusesARegistrationForADifferentChallenge()
    {
        // The single most important refusal. Without it, an attacker who once
        // saw a valid response replays it for ever.
        Result<VerifiedRegistration> result = VerifierFor().VerifyRegistration(
            Captured.RegistrationEvidence(),
            Base64Url.EncodeToString("a challenge nobody issued"u8.ToArray()));

        Assert.True(result.IsFailure);
        Assert.Equal(IdentityErrors.InvalidPasskeyRegistration.Code, result.Error.Code);
    }

    [Fact]
    public void RefusesARegistrationFromAnotherOrigin()
    {
        // What stops a convincing copy of the sign-in page on another domain
        // from collecting a usable credential.
        Result<VerifiedRegistration> result = VerifierFor(origin: "https://not-the-platform.example")
            .VerifyRegistration(Captured.RegistrationEvidence(), Captured.Registration.Challenge);

        Assert.True(result.IsFailure);
    }

    [Fact]
    public void RefusesARegistrationForAnotherRelyingParty()
    {
        // The origin is the browser's claim; the relying-party hash inside the
        // authenticator data is the device's, and they are checked separately
        // because different parties assert them.
        Result<VerifiedRegistration> result = VerifierFor(relyingPartyId: "somewhere.else")
            .VerifyRegistration(Captured.RegistrationEvidence(), Captured.Registration.Challenge);

        Assert.True(result.IsFailure);
    }

    [Fact]
    public void RefusesASignInResponseOfferedAsARegistration()
    {
        // The ceremony type is signed over. A signature collected during one
        // must not be usable as the other.
        Result<VerifiedRegistration> result = VerifierFor().VerifyRegistration(
            new PasskeyRegistrationEvidence(
                Captured.Authentication.ClientDataJson,
                Captured.Registration.AttestationObject),
            Captured.Authentication.Challenge);

        Assert.True(result.IsFailure);
    }

    [Fact]
    public void RefusesARegistrationRunInsideAnotherSitesFrame()
    {
        // The person cannot see whose page they are answering for.
        Result<VerifiedRegistration> result = VerifierFor().VerifyRegistration(
            new PasskeyRegistrationEvidence(
                Vectors.ClientDataWith(Captured.Registration.ClientDataJson, "crossOrigin", true),
                Captured.Registration.AttestationObject),
            Captured.Registration.Challenge);

        Assert.True(result.IsFailure);
    }

    [Fact]
    public void RefusesAnythingThatIsNotAValidResponse()
    {
        // A malformed body is a refusal, not a five hundred.
        foreach (string rubbish in new[] { string.Empty, "not-base64url!!", "AAAA", "eyJhIjoxfQ" })
        {
            Result<VerifiedRegistration> result = VerifierFor().VerifyRegistration(
                new PasskeyRegistrationEvidence(rubbish, rubbish),
                Captured.Registration.Challenge);

            Assert.True(result.IsFailure, rubbish);
        }
    }

    // -----------------------------------------------------------------------
    // Signing in
    // -----------------------------------------------------------------------

    [Fact]
    public void AcceptsAnAssertionChromeProduced()
    {
        VerifiedRegistration registered = Registered();

        Result<VerifiedAssertion> result = VerifierFor().VerifyAssertion(
            Captured.AssertionEvidence(),
            Captured.Authentication.Challenge,
            registered.PublicKey,
            registered.Algorithm);

        Assert.True(result.IsSuccess, result.IsFailure ? result.Error.Code : null);
        Assert.True(result.Value.UserVerified);

        // The account the credential was created for, which is how a sign-in
        // that carries no username knows whose it is.
        Assert.Equal(Captured.UserHandleAsGuid, result.Value.UserHandle);
    }

    [Fact]
    public void RefusesAnAssertionForADifferentChallenge()
    {
        VerifiedRegistration registered = Registered();

        Result<VerifiedAssertion> result = VerifierFor().VerifyAssertion(
            Captured.AssertionEvidence(),
            Captured.Registration.Challenge,
            registered.PublicKey,
            registered.Algorithm);

        Assert.True(result.IsFailure);
        Assert.Equal(IdentityErrors.InvalidPasskeyAssertion.Code, result.Error.Code);
    }

    [Fact]
    public void RefusesAnAssertionWhoseSignatureWasTamperedWith()
    {
        VerifiedRegistration registered = Registered();

        byte[] signature = Base64Url.DecodeFromChars(Captured.Authentication.Signature);

        // One bit, in the last byte.
        signature[^1] ^= 0x01;

        Result<VerifiedAssertion> result = VerifierFor().VerifyAssertion(
            Captured.AssertionEvidence() with { Signature = Base64Url.EncodeToString(signature) },
            Captured.Authentication.Challenge,
            registered.PublicKey,
            registered.Algorithm);

        Assert.True(result.IsFailure);
    }

    [Fact]
    public void RefusesAnAssertionVerifiedAgainstSomebodyElsesKey()
    {
        VerifiedRegistration registered = Registered();

        byte[] otherKey = [.. registered.PublicKey];

        // Change the key material, not the structure, so it still parses.
        otherKey[^1] ^= 0xFF;

        Result<VerifiedAssertion> result = VerifierFor().VerifyAssertion(
            Captured.AssertionEvidence(),
            Captured.Authentication.Challenge,
            otherKey,
            registered.Algorithm);

        Assert.True(result.IsFailure);
    }

    [Fact]
    public void RefusesAnAssertionWhoseAuthenticatorDataWasTamperedWith()
    {
        VerifiedRegistration registered = Registered();

        byte[] authenticatorData = Base64Url.DecodeFromChars(Captured.Authentication.AuthenticatorData);

        // The counter. Altering it breaks the signature, which is the point:
        // the device signs over its own data, so nothing in it can be edited in
        // flight.
        authenticatorData[^1] ^= 0x7F;

        Result<VerifiedAssertion> result = VerifierFor().VerifyAssertion(
            Captured.AssertionEvidence() with
            {
                AuthenticatorData = Base64Url.EncodeToString(authenticatorData),
            },
            Captured.Authentication.Challenge,
            registered.PublicKey,
            registered.Algorithm);

        Assert.True(result.IsFailure);
    }

    [Fact]
    public void RefusesAnAssertionWhoseAuthenticatorDidNotVerifyThePerson()
    {
        // A key in a pocket rather than a person at a device. Said plainly to
        // the caller, because it is the one refusal they can do something
        // about: turn on a fingerprint or a device passcode.
        VerifiedRegistration registered = Registered();

        byte[] authenticatorData = Base64Url.DecodeFromChars(Captured.Authentication.AuthenticatorData);

        authenticatorData[32] &= 0xFB;

        Result<VerifiedAssertion> result = VerifierFor().VerifyAssertion(
            Captured.AssertionEvidence() with
            {
                AuthenticatorData = Base64Url.EncodeToString(authenticatorData),
            },
            Captured.Authentication.Challenge,
            registered.PublicKey,
            registered.Algorithm);

        Assert.True(result.IsFailure);
        Assert.Equal(IdentityErrors.PasskeyUserVerificationRequired.Code, result.Error.Code);
    }

    [Fact]
    public void RefusesARegistrationResponseOfferedAsASignIn()
    {
        VerifiedRegistration registered = Registered();

        Result<VerifiedAssertion> result = VerifierFor().VerifyAssertion(
            Captured.AssertionEvidence() with { ClientDataJson = Captured.Registration.ClientDataJson },
            Captured.Registration.Challenge,
            registered.PublicKey,
            registered.Algorithm);

        Assert.True(result.IsFailure);
    }

    private static VerifiedRegistration Registered()
    {
        Result<VerifiedRegistration> result = VerifierFor().VerifyRegistration(
            Captured.RegistrationEvidence(),
            Captured.Registration.Challenge);

        Assert.True(result.IsSuccess, result.IsFailure ? result.Error.Code : null);

        return result.Value;
    }

    // -----------------------------------------------------------------------

    private sealed record Vectors(
        string RelyingPartyId,
        string Origin,
        string UserHandle,
        RegistrationVector Registration,
        AuthenticationVector Authentication)
    {
        private static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);

        public static Vectors Load()
        {
            string path = Path.Combine(AppContext.BaseDirectory, "webauthn-vectors.json");

            return JsonSerializer.Deserialize<Vectors>(File.ReadAllText(path), Json)
                ?? throw new InvalidOperationException("The captured vectors did not parse.");
        }

        public Guid UserHandleAsGuid => new(Base64Url.DecodeFromChars(UserHandle), bigEndian: true);

        public PasskeyRegistrationEvidence RegistrationEvidence()
            => new(Registration.ClientDataJson, Registration.AttestationObject);

        public PasskeyAssertionEvidence AssertionEvidence()
            => new(
                Authentication.CredentialId,
                Authentication.ClientDataJson,
                Authentication.AuthenticatorData,
                Authentication.Signature,
                Authentication.UserHandle);

        /// <summary>
        /// The same client data with one field changed, for the checks that are
        /// about what the browser said rather than about the signature.
        /// </summary>
        public static string ClientDataWith(string clientDataJson, string property, bool value)
        {
            Dictionary<string, JsonElement> fields =
                JsonSerializer.Deserialize<Dictionary<string, JsonElement>>(
                    Base64Url.DecodeFromChars(clientDataJson))!;

            fields[property] = JsonSerializer.SerializeToElement(value);

            return Base64Url.EncodeToString(
                Encoding.UTF8.GetBytes(JsonSerializer.Serialize(fields)));
        }
    }

    private sealed record RegistrationVector(
        string Challenge,
        string CredentialId,
        string ClientDataJson,
        string AttestationObject);

    private sealed record AuthenticationVector(
        string Challenge,
        string CredentialId,
        string ClientDataJson,
        string AuthenticatorData,
        string Signature,
        string? UserHandle);
}
