/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/diagnostics/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Confirms the API is reachable and returns the correlation id. */
        get: operations["Ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics/error/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns each error category so the contract can be verified. */
        get: operations["ErrorContract"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics/paged": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns a paged envelope so paging and sorting rules can be verified. */
        get: operations["PagedSample"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics/throw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Raises an unhandled exception to verify the error boundary. */
        get: operations["ThrowSample"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticates a user and starts a session. */
        post: operations["SignIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchanges a refresh token for a new token pair. */
        post: operations["RefreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ends the current session, revoking its tokens server-side. */
        post: operations["SignOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Changes the caller's password and ends their other sessions. */
        post: operations["ChangePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Requests a password reset link. Always succeeds, revealing nothing. */
        post: operations["ForgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redeems a reset token and sets a new password. */
        post: operations["ResetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the signed-in user's profile. */
        get: operations["GetCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists the caller's active sessions. */
        get: operations["GetMySessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/login-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists the caller's recent sign-in attempts, successful and failed. */
        get: operations["GetMyLoginHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists users, filtered and paged. */
        get: operations["SearchUsers"];
        put?: never;
        /** Creates a user who must change their password at first sign-in. */
        post: operations["CreateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns one user. */
        get: operations["GetUser"];
        /** Updates a user's email and display name. */
        put: operations["UpdateUser"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enables a user account. */
        post: operations["EnableUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disables a user account. */
        post: operations["DisableUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/unlock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unlocks a user account. */
        post: operations["UnlockUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/.well-known/jwks.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public keys for validating Platform access tokens locally. */
        get: operations["Jwks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists the caller's permissions, for hiding controls they cannot use. */
        get: operations["GetMyPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/authorization/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answers whether a user holds a permission, and over what data. */
        post: operations["CheckPermission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/security/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Searches the security event log within a bounded time window. */
        get: operations["SearchSecurityEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/company": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the company, or null when the Platform has not been set up yet. */
        get: operations["GetCompany"];
        put?: never;
        /** Establishes the company. Refused once one exists. */
        post: operations["CreateCompany"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/company/name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Renames the company in both languages. Its code is fixed. */
        put: operations["RenameCompany"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/units/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the company structure as a nested tree. */
        get: operations["GetOrganizationTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creates an organizational unit under an optional parent. */
        post: operations["CreateOrganizationUnit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/units/{id}/name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Renames a unit in both languages. */
        put: operations["RenameOrganizationUnit"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/units/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Moves a unit and every descendant to a new parent, atomically. */
        post: operations["MoveOrganizationUnit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/units/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivates a unit that has no active children or employees. */
        post: operations["DeactivateOrganizationUnit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists the company's job positions. */
        get: operations["GetPositions"];
        put?: never;
        /** Creates a job position. */
        post: operations["CreatePosition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/positions/{id}/title": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Renames a position in both languages. */
        put: operations["RenamePosition"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/positions/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivates a position, or brings it back. Never deletes one. */
        post: operations["SetPositionStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists employees, optionally scoped to a unit and everything beneath it. */
        get: operations["SearchEmployees"];
        put?: never;
        /** Creates an employee record. */
        post: operations["CreateEmployee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/employees/{id}/transfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Moves an employee to a different unit, position or manager. */
        post: operations["TransferEmployee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/employees/{id}/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Links or unlinks an employee's Platform account. */
        put: operations["LinkEmployeeUser"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists roles. */
        get: operations["GetRoles"];
        put?: never;
        /** Creates a role. It starts empty; its permissions are set separately. */
        post: operations["CreateRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists every declared permission, including those of registered applications. */
        get: operations["GetPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns one role with the permissions it carries. */
        get: operations["GetRole"];
        /** Renames a role. The code is fixed once created. */
        put: operations["UpdateRole"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/{id}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replaces the permissions a role carries, refusing any the caller does not hold. */
        put: operations["SetRolePermissions"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivates a role, or brings it back. Never deletes one. */
        post: operations["SetRoleStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists a user's role assignments. */
        get: operations["GetUserRoles"];
        put?: never;
        /** Grants a role at a scope, refusing any escalation. */
        post: operations["GrantRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/roles/{assignmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revokes a role assignment. Takes effect on the next request. */
        delete: operations["RevokeRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/mfa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns whether the caller has two-factor authentication enabled. */
        get: operations["GetMfaStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/mfa/enrol": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issues a TOTP secret. Returns the QR data once and never again. */
        post: operations["BeginMfaEnrolment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/mfa/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activates enrolment and returns recovery codes, shown once. */
        post: operations["ConfirmMfaEnrolment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/mfa/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verifies a TOTP or recovery code. */
        post: operations["VerifyMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/mfa/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Turns off two-factor authentication, after proving the current factor. */
        post: operations["DisableMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Searches the audit trail. The date range is required and bounded. */
        get: operations["SearchAuditEvents"];
        put?: never;
        /** Records one event, attributed to the calling application. */
        post: operations["IngestAuditEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/events/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Records many events at once, attributed to the calling application. */
        post: operations["IngestAuditEventBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflow/definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists the registered approval processes. */
        get: operations["GetWorkflowDefinitions"];
        put?: never;
        /** Registers and publishes a version of an approval process. */
        post: operations["RegisterWorkflowDefinition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflow/definitions/{id}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stops new instances starting on a version. Running ones continue. */
        post: operations["RetireWorkflowDefinition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflow/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Finds approvals, usually by the record they belong to. */
        get: operations["SearchWorkflowInstances"];
        put?: never;
        /** Starts an approval against a business record. */
        post: operations["StartWorkflowInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflow/instances/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns one approval with everything that happened to it. */
        get: operations["GetWorkflowInstance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflow/instances/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Withdraws an approval and closes every task on it. */
        post: operations["CancelWorkflowInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's approval inbox. */
        get: operations["GetMyTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/tasks/{id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approves, rejects, returns, delegates or comments on a task. */
        post: operations["ActOnTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuditEventDto: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            occurredAt: string;
            application: string;
            module: string;
            action: string;
            result: string;
            resourceType: null | string;
            resourceId: null | string;
            /** Format: uuid */
            actorUserId: null | string;
            actorUsername: null | string;
            /** Format: uuid */
            onBehalfOfUserId: null | string;
            ipAddress: null | string;
            correlationId: null | string;
            oldValue: null | string;
            newValue: null | string;
            metadata: null | string;
        };
        AuthenticationResultDto: {
            accessToken: string;
            refreshToken: string;
            /** Format: int32 */
            expiresInSeconds: number | string;
            tokenType: string;
            user: components["schemas"]["CurrentUserDto"];
        };
        CancelInstanceRequest: {
            reason?: null | string;
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        CheckPermissionRequest: {
            permission: string;
            /** Format: uuid */
            userId: null | string;
        };
        CompanyDto: {
            /** Format: uuid */
            id: string;
            code: string;
            name: components["schemas"]["LocalizedNameDto"];
            defaultLocale: string;
            isActive: boolean;
        };
        CreateCompanyRequest: {
            code: string;
            nameAr: string;
            nameEn: string;
            defaultLocale?: null | string;
        };
        CreateEmployeeRequest: {
            employeeNumber: string;
            fullNameAr: string;
            fullNameEn: string;
            /** Format: uuid */
            unitId: string;
            /** Format: uuid */
            positionId?: null | string;
            /** Format: uuid */
            managerId?: null | string;
            /** Format: uuid */
            userId?: null | string;
            workEmail?: null | string;
            workPhone?: null | string;
            /** Format: date */
            hireDate?: null | string;
        };
        CreatePositionRequest: {
            code: string;
            titleAr: string;
            titleEn: string;
            /** Format: int32 */
            level?: null | number | string;
        };
        CreateRoleRequest: {
            code: string;
            nameAr: string;
            nameEn: string;
            description?: null | string;
        };
        CreateUnitRequest: {
            /** Format: uuid */
            parentId: null | string;
            unitType: string;
            code: string;
            nameAr: string;
            nameEn: string;
            parsedUnitType?: components["schemas"]["OrganizationUnitType"];
        };
        CreateUserRequest: {
            username: string;
            email: string;
            displayName: string;
            initialPassword: string;
        };
        CurrentUserDto: {
            /** Format: uuid */
            id: string;
            username: string;
            email: string;
            displayName: string;
            mustChangePassword: boolean;
            /** Format: uuid */
            sessionId: string;
        };
        EmployeeDto: {
            /** Format: uuid */
            id: string;
            employeeNumber: string;
            fullName: components["schemas"]["LocalizedNameDto"];
            /** Format: uuid */
            userId: null | string;
            /** Format: uuid */
            unitId: string;
            unitCode: string;
            /** Format: uuid */
            positionId: null | string;
            positionCode: null | string;
            /** Format: uuid */
            managerId: null | string;
            workEmail: null | string;
            workPhone: null | string;
            /** Format: date */
            hireDate: null | string;
            isActive: boolean;
        };
        ForgotPasswordRequest: {
            email: null | string;
        };
        GrantRoleRequest: {
            /** Format: uuid */
            roleId: string;
            scope: string;
            /** Format: uuid */
            scopeUnitId: null | string;
            /** Format: date-time */
            expiresAt: null | string;
            parsedScope?: components["schemas"]["ScopeType"];
        };
        IngestAuditEventDto: {
            module: string;
            action: string;
            /** Format: date-time */
            occurredAt: null | string;
            result: null | string;
            resourceType: null | string;
            resourceId: null | string;
            /** Format: uuid */
            actorUserId: null | string;
            actorUsername: null | string;
            /** Format: uuid */
            onBehalfOfUserId: null | string;
            oldValue: null | string;
            newValue: null | string;
            metadata: null | string;
        };
        LinkUserRequest: {
            /** Format: uuid */
            userId: null | string;
        };
        LocalizedNameDto: {
            ar: string;
            en: string;
        };
        LoginAttemptDto: {
            succeeded: boolean;
            ipAddress: null | string;
            userAgent: null | string;
            /** Format: date-time */
            occurredAt: string;
        };
        LoginRequest: {
            username: string;
            password: string;
            deviceFingerprint: null | string;
        };
        MfaCodeRequest: {
            code: string;
        };
        MfaEnrolmentDto: {
            provisioningUri: string;
            manualEntryKey: string;
        };
        MfaStatusDto: {
            isEnrolled: boolean;
            isActive: boolean;
            /** Format: date-time */
            activatedAt: null | string;
            /** Format: date-time */
            lastUsedAt: null | string;
            /** Format: int32 */
            remainingRecoveryCodes: number | string;
        };
        MfaVerificationDto: {
            verified: boolean;
            usedRecoveryCode: boolean;
            /** Format: int32 */
            remainingRecoveryCodes: number | string;
            /** Format: date-time */
            stepUpValidUntil: string;
        };
        MfaVerifyRequest: {
            code: string;
            isRecoveryCode: null | boolean;
        };
        MoveUnitRequest: {
            /** Format: uuid */
            newParentId: null | string;
        };
        MyPermissionsDto: {
            permissions: string[];
            hasOrganizationalUnit: boolean;
        };
        OrganizationUnitDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            parentId: null | string;
            unitType: string;
            code: string;
            name: components["schemas"]["LocalizedNameDto"];
            /** Format: int32 */
            depth: number | string;
            /** Format: int32 */
            sortOrder: number | string;
            isActive: boolean;
        };
        OrganizationUnitTreeDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            parentId: null | string;
            unitType: string;
            code: string;
            name: components["schemas"]["LocalizedNameDto"];
            /** Format: int32 */
            depth: number | string;
            /** Format: int32 */
            sortOrder: number | string;
            isActive: boolean;
            children: components["schemas"]["OrganizationUnitTreeDto"][];
        };
        OrganizationUnitType: number;
        PagedResultOfAuditEventDto: {
            items: components["schemas"]["AuditEventDto"][];
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int64 */
            totalItems: number | string;
            /** Format: int32 */
            totalPages?: number | string;
            hasPrevious?: boolean;
            hasNext?: boolean;
        };
        PagedResultOfEmployeeDto: {
            items: components["schemas"]["EmployeeDto"][];
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int64 */
            totalItems: number | string;
            /** Format: int32 */
            totalPages?: number | string;
            hasPrevious?: boolean;
            hasNext?: boolean;
        };
        PagedResultOfSecurityEventDto: {
            items: components["schemas"]["SecurityEventDto"][];
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int64 */
            totalItems: number | string;
            /** Format: int32 */
            totalPages?: number | string;
            hasPrevious?: boolean;
            hasNext?: boolean;
        };
        PagedResultOfUserDto: {
            items: components["schemas"]["UserDto"][];
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int64 */
            totalItems: number | string;
            /** Format: int32 */
            totalPages?: number | string;
            hasPrevious?: boolean;
            hasNext?: boolean;
        };
        PagedResultOfWorkflowInstanceDto: {
            items: components["schemas"]["WorkflowInstanceDto"][];
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int64 */
            totalItems: number | string;
            /** Format: int32 */
            totalPages?: number | string;
            hasPrevious?: boolean;
            hasNext?: boolean;
        };
        PagedResultOfWorkflowTaskDto: {
            items: components["schemas"]["WorkflowTaskDto"][];
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int64 */
            totalItems: number | string;
            /** Format: int32 */
            totalPages?: number | string;
            hasPrevious?: boolean;
            hasNext?: boolean;
        };
        PermissionDto: {
            /** Format: uuid */
            id: string;
            name: string;
            application: string;
            resource: string;
            action: string;
            description: string;
            isActive: boolean;
        };
        PositionDto: {
            /** Format: uuid */
            id: string;
            code: string;
            title: components["schemas"]["LocalizedNameDto"];
            /** Format: int32 */
            level: null | number | string;
            isActive: boolean;
        };
        RecoveryCodesDto: {
            codes: string[];
            /** Format: int32 */
            count: number | string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        RegisterDefinitionRequest: {
            applicationCode: string;
            code: string;
            /** Format: int32 */
            version: number | string;
            nameAr: string;
            nameEn: string;
            steps: components["schemas"]["StepRequest"][];
            description?: null | string;
            initialStepKey?: null | string;
        };
        RenameCompanyRequest: {
            nameAr: string;
            nameEn: string;
        };
        RenamePositionRequest: {
            titleAr: string;
            titleEn: string;
        };
        RenameUnitRequest: {
            nameAr: string;
            nameEn: string;
        };
        ResetPasswordRequest: {
            token: string;
            newPassword: string;
        };
        RoleDetailDto: {
            /** Format: uuid */
            id: string;
            code: string;
            nameAr: string;
            nameEn: string;
            description: null | string;
            isSystem: boolean;
            isActive: boolean;
            permissionIds: string[];
        };
        RoleDto: {
            /** Format: uuid */
            id: string;
            code: string;
            nameAr: string;
            nameEn: string;
            description: null | string;
            isSystem: boolean;
            isActive: boolean;
            /** Format: int32 */
            permissionCount: number | string;
        };
        ScopeType: number;
        SecurityEventDto: {
            /** Format: uuid */
            id: string;
            eventType: string;
            severity: string;
            /** Format: uuid */
            userId: null | string;
            username: null | string;
            ipAddress: null | string;
            details: null | string;
            correlationId: null | string;
            /** Format: date-time */
            occurredAt: string;
        };
        SessionDto: {
            /** Format: uuid */
            id: string;
            ipAddress: null | string;
            userAgent: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastActivityAt: string;
            /** Format: date-time */
            absoluteExpiresAt: string;
            isCurrent: boolean;
        };
        SetPositionActiveRequest: {
            isActive: boolean;
        };
        SetRoleActiveRequest: {
            isActive: boolean;
        };
        SetRolePermissionsRequest: {
            permissionIds: string[];
        };
        StartInstanceRequest: {
            applicationCode: string;
            definitionCode: string;
            resourceType: string;
            resourceId: string;
            assignees?: null | string[];
        };
        StepRequest: {
            key: string;
            nameAr: string;
            nameEn: string;
            /** Format: int32 */
            order: number | string;
            assigneeStrategy: string;
            /** Format: uuid */
            assigneeUserId?: null | string;
            /** Format: uuid */
            assigneeRoleId?: null | string;
            /** Format: uuid */
            assigneePositionId?: null | string;
            /** Format: uuid */
            assigneeUnitId?: null | string;
            /** Format: double */
            serviceLevelHours?: null | number | string;
            transitions?: null | components["schemas"]["TransitionRequest"][];
        };
        TaskActionRequest: {
            action: string;
            comment?: null | string;
            /** Format: uuid */
            delegateToUserId?: null | string;
            parsedAction?: components["schemas"]["WorkflowActionType"];
        };
        TransferEmployeeRequest: {
            /** Format: uuid */
            newUnitId: string;
            /** Format: uuid */
            newPositionId: null | string;
            /** Format: uuid */
            newManagerId: null | string;
        };
        TransitionRequest: {
            action: string;
            targetStepKey?: null | string;
        };
        UpdateRoleRequest: {
            nameAr: string;
            nameEn: string;
            description?: null | string;
        };
        UpdateUserRequest: {
            email: string;
            displayName: string;
        };
        UserDto: {
            /** Format: uuid */
            id: string;
            username: string;
            email: string;
            emailVerified: boolean;
            displayName: string;
            status: string;
            mustChangePassword: boolean;
            /** Format: date-time */
            lastLoginAt: null | string;
            /** Format: date-time */
            createdAt: string;
        };
        UserRoleDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            roleId: string;
            scopeType: string;
            /** Format: uuid */
            scopeUnitId: null | string;
            /** Format: uuid */
            grantedBy: string;
            /** Format: date-time */
            grantedAt: string;
            /** Format: date-time */
            expiresAt: null | string;
            /** Format: date-time */
            revokedAt: null | string;
        };
        WorkflowActionDto: {
            stepKey: string;
            action: string;
            /** Format: uuid */
            actorUserId: string;
            comment: null | string;
            /** Format: date-time */
            occurredAt: string;
        };
        WorkflowActionType: number;
        WorkflowDefinitionDto: {
            /** Format: uuid */
            id: string;
            applicationCode: string;
            code: string;
            /** Format: int32 */
            version: number | string;
            nameAr: string;
            nameEn: string;
            description: null | string;
            status: string;
            initialStepKey: null | string;
            steps: components["schemas"]["WorkflowStepDto"][];
        };
        WorkflowInstanceDto: {
            /** Format: uuid */
            id: string;
            applicationCode: string;
            definitionCode: string;
            /** Format: int32 */
            definitionVersion: number | string;
            resourceType: string;
            resourceId: string;
            /** Format: uuid */
            requestedBy: string;
            currentStepKey: null | string;
            status: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            completedAt: null | string;
            actions: components["schemas"]["WorkflowActionDto"][];
        };
        WorkflowStepDto: {
            key: string;
            nameAr: string;
            nameEn: string;
            /** Format: int32 */
            order: number | string;
            assigneeStrategy: string;
            /** Format: uuid */
            assigneeUserId: null | string;
            /** Format: uuid */
            assigneeRoleId: null | string;
            /** Format: uuid */
            assigneePositionId: null | string;
            /** Format: uuid */
            assigneeUnitId: null | string;
            /** Format: double */
            serviceLevelHours: null | number | string;
            transitions: components["schemas"]["WorkflowTransitionDto"][];
        };
        WorkflowTaskDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            instanceId: string;
            applicationCode: string;
            definitionCode: string;
            resourceType: string;
            resourceId: string;
            stepKey: string;
            stepNameAr: string;
            stepNameEn: string;
            /** Format: uuid */
            assignedToUserId: string;
            /** Format: uuid */
            delegatedFromUserId: null | string;
            status: string;
            /** Format: date-time */
            assignedAt: string;
            /** Format: date-time */
            dueAt: null | string;
            isOverdue: boolean;
            allowedActions: string[];
        };
        WorkflowTransitionDto: {
            action: string;
            targetStepKey: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ErrorContract: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PagedSample: {
        parameters: {
            query?: {
                page?: number | string;
                pageSize?: number | string;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ThrowSample: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SignIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationResultDto"];
                };
            };
        };
    };
    RefreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationResultDto"];
                };
            };
        };
    };
    SignOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChangePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ForgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    GetMySessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"][];
                };
            };
        };
    };
    GetMyLoginHistory: {
        parameters: {
            query?: {
                count?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginAttemptDto"][];
                };
            };
        };
    };
    SearchUsers: {
        parameters: {
            query?: {
                page?: number | string;
                pageSize?: number | string;
                sort?: string;
                q?: string;
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfUserDto"];
                };
            };
        };
    };
    CreateUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    GetUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    UpdateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    EnableUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DisableUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UnlockUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Jwks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetMyPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyPermissionsDto"];
                };
            };
        };
    };
    CheckPermission: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckPermissionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SearchSecurityEvents: {
        parameters: {
            query?: {
                page?: number | string;
                pageSize?: number | string;
                userId?: string;
                eventType?: string;
                minimumSeverity?: string;
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfSecurityEventDto"];
                };
            };
        };
    };
    GetCompany: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDto"];
                };
            };
        };
    };
    CreateCompany: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCompanyRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDto"];
                };
            };
        };
    };
    RenameCompany: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameCompanyRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDto"];
                };
            };
        };
    };
    GetOrganizationTree: {
        parameters: {
            query?: {
                includeInactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationUnitTreeDto"][];
                };
            };
        };
    };
    CreateOrganizationUnit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUnitRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationUnitDto"];
                };
            };
        };
    };
    RenameOrganizationUnit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameUnitRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationUnitDto"];
                };
            };
        };
    };
    MoveOrganizationUnit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveUnitRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeactivateOrganizationUnit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetPositions: {
        parameters: {
            query?: {
                includeInactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionDto"][];
                };
            };
        };
    };
    CreatePosition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePositionRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionDto"];
                };
            };
        };
    };
    RenamePosition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenamePositionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionDto"];
                };
            };
        };
    };
    SetPositionStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPositionActiveRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SearchEmployees: {
        parameters: {
            query?: {
                page?: number | string;
                pageSize?: number | string;
                sort?: string;
                q?: string;
                unitId?: string;
                includeSubUnits?: boolean;
                isActive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfEmployeeDto"];
                };
            };
        };
    };
    CreateEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEmployeeRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeDto"];
                };
            };
        };
    };
    TransferEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferEmployeeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LinkEmployeeUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetRoles: {
        parameters: {
            query?: {
                includeInactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleDto"][];
                };
            };
        };
    };
    CreateRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleDto"];
                };
            };
        };
    };
    GetPermissions: {
        parameters: {
            query?: {
                includeInactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionDto"][];
                };
            };
        };
    };
    GetRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleDetailDto"];
                };
            };
        };
    };
    UpdateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleDto"];
                };
            };
        };
    };
    SetRolePermissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetRolePermissionsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleDto"];
                };
            };
        };
    };
    SetRoleStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetRoleActiveRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetUserRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRoleDto"][];
                };
            };
        };
    };
    GrantRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantRoleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RevokeRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                assignmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetMfaStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaStatusDto"];
                };
            };
        };
    };
    BeginMfaEnrolment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaEnrolmentDto"];
                };
            };
        };
    };
    ConfirmMfaEnrolment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaCodeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryCodesDto"];
                };
            };
        };
    };
    VerifyMfa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaVerifyRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaVerificationDto"];
                };
            };
        };
    };
    DisableMfa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaCodeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SearchAuditEvents: {
        parameters: {
            query?: {
                From?: string;
                To?: string;
                Application?: string;
                Module?: string;
                Action?: string;
                ActorUserId?: string;
                ResourceType?: string;
                ResourceId?: string;
                Result?: string;
                Page?: number | string;
                PageSize?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfAuditEventDto"];
                };
            };
        };
    };
    IngestAuditEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestAuditEventDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IngestAuditEventBatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestAuditEventDto"][];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetWorkflowDefinitions: {
        parameters: {
            query?: {
                applicationCode?: string;
                includeRetired?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinitionDto"][];
                };
            };
        };
    };
    RegisterWorkflowDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDefinitionRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinitionDto"];
                };
            };
        };
    };
    RetireWorkflowDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SearchWorkflowInstances: {
        parameters: {
            query?: {
                applicationCode?: string;
                resourceType?: string;
                resourceId?: string;
                status?: string;
                page?: number | string;
                pageSize?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfWorkflowInstanceDto"];
                };
            };
        };
    };
    StartWorkflowInstance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartInstanceRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowInstanceDto"];
                };
            };
        };
    };
    GetWorkflowInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowInstanceDto"];
                };
            };
        };
    };
    CancelWorkflowInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelInstanceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetMyTasks: {
        parameters: {
            query?: {
                includeCompleted?: boolean;
                page?: number | string;
                pageSize?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfWorkflowTaskDto"];
                };
            };
        };
    };
    ActOnTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskActionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowInstanceDto"];
                };
            };
        };
    };
}
