<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Modules\Authorization\CCP.Modules.Authorization.Domain\CCP.Modules.Authorization.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Authorization\CCP.Modules.Authorization.Application\CCP.Modules.Authorization.Application.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Authorization\CCP.Modules.Authorization.Infrastructure\CCP.Modules.Authorization.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Authorization\CCP.Modules.Authorization.Contracts\CCP.Modules.Authorization.Contracts.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Authorization\CCP.Modules.Authorization.Api\CCP.Modules.Authorization.Api.csproj" />
    <ProjectReference Include="..\..\..\src\Kernel\CCP.Kernel.Api\CCP.Kernel.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>